CREATE OR REPLACE FUNCTION QUERY_OPTIMIZATION_DB.AGENT.GET_UNANALYZED_QUERIES()
RETURNS TABLE ("CAPTURE_ID" NUMBER(38,0), "QUERY_ID" VARCHAR, "WAREHOUSE_NAME" VARCHAR, "WAREHOUSE_SIZE" VARCHAR, "USER_NAME" VARCHAR, "QUERY_TYPE" VARCHAR, "EXECUTION_STATUS" VARCHAR, "TOTAL_ELAPSED_TIME_SEC" FLOAT, "TOTAL_COST_USD" FLOAT, "GB_SCANNED" FLOAT, "PERCENTAGE_SCANNED_FROM_CACHE" FLOAT, "PARTITION_SCAN_PCT" FLOAT, "SPILL_STATUS" VARCHAR, "QUEUE_STATUS" VARCHAR, "QUERY_TEXT" VARCHAR)
LANGUAGE SQL
AS '
    SELECT 
        CAPTURE_ID,
        QUERY_ID,
        WAREHOUSE_NAME,
        WAREHOUSE_SIZE,
        USER_NAME,
        QUERY_TYPE,
        EXECUTION_STATUS,
        TOTAL_ELAPSED_TIME_SEC,
        TOTAL_COST_USD,
        GB_SCANNED,
        PERCENTAGE_SCANNED_FROM_CACHE,
        PARTITION_SCAN_PCT,
        SPILL_STATUS,
        QUEUE_STATUS,
        QUERY_TEXT
    FROM QUERY_OPTIMIZATION_DB.AGENT.BAD_QUERIES_RAW
    WHERE IS_ANALYZED = FALSE
    ORDER BY TOTAL_COST_USD DESC
    LIMIT 10
';

CREATE OR REPLACE FUNCTION QUERY_OPTIMIZATION_DB.AGENT.GET_UNANALYZED_QUERIES_JSON()
RETURNS ARRAY
LANGUAGE SQL
AS '
    SELECT ARRAY_AGG(OBJECT_CONSTRUCT(
        ''capture_id'', CAPTURE_ID,
        ''query_id'', QUERY_ID,
        ''warehouse_name'', WAREHOUSE_NAME,
        ''warehouse_size'', WAREHOUSE_SIZE,
        ''user_name'', USER_NAME,
        ''query_type'', QUERY_TYPE,
        ''execution_status'', EXECUTION_STATUS,
        ''total_elapsed_time_sec'', TOTAL_ELAPSED_TIME_SEC,
        ''total_cost_usd'', TOTAL_COST_USD,
        ''gb_scanned'', GB_SCANNED,
        ''cache_hit_pct'', PERCENTAGE_SCANNED_FROM_CACHE,
        ''partition_scan_pct'', PARTITION_SCAN_PCT,
        ''spill_status'', SPILL_STATUS,
        ''queue_status'', QUEUE_STATUS,
        ''query_text'', LEFT(QUERY_TEXT, 2000)
    ))
    FROM (
        SELECT * FROM QUERY_OPTIMIZATION_DB.AGENT.BAD_QUERIES_RAW
        WHERE IS_ANALYZED = FALSE
        ORDER BY TOTAL_COST_USD DESC
        LIMIT 5
    )
';

