create or replace TABLE AI_TREND_INSIGHTS (
    INSIGHT_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
    ANALYSIS_DATE DATE,
    INSIGHT_TYPE VARCHAR(16777216),
    WAREHOUSE_NAME VARCHAR(16777216),
    INSIGHT_SUMMARY VARCHAR(5000),
    AI_RECOMMENDATIONS VARCHAR(10000),
    METRICS_SNAPSHOT OBJECT,
    CREATED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE ALERT_PROCESSING (
    ALERT_ID NUMBER(38,0),
    EMAIL_TO VARCHAR(16777216),
    SUBJECT VARCHAR(16777216),
    BODY VARCHAR(16000)
);

create or replace TABLE ALERT_QUEUE (
    ALERT_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
    CREATED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    EMAIL_TO VARCHAR(16777216),
    SUBJECT VARCHAR(16777216),
    BODY VARCHAR(16000),
    IS_SENT BOOLEAN DEFAULT FALSE
);

create or replace TABLE BAD_QUERIES_RAW (
    CAPTURE_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
    CAPTURE_TIMESTAMP TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    QUERY_ID VARCHAR(16777216),
    WAREHOUSE_NAME VARCHAR(16777216),
    WAREHOUSE_SIZE VARCHAR(16777216),
    USER_NAME VARCHAR(16777216),
    ROLE_NAME VARCHAR(16777216),
    QUERY_TYPE VARCHAR(16777216),
    EXECUTION_STATUS VARCHAR(16777216),
    QUERY_DATE DATE,
    TOTAL_ELAPSED_TIME_SEC FLOAT,
    TOTAL_CREDITS FLOAT,
    TOTAL_COST_USD FLOAT,
    GB_SCANNED FLOAT,
    PERCENTAGE_SCANNED_FROM_CACHE FLOAT,
    PARTITION_SCAN_PCT FLOAT,
    SPILL_STATUS VARCHAR(16777216),
    QUEUE_STATUS VARCHAR(16777216),
    QUERY_TEXT VARCHAR(16000),
    CLIENT_APPLICATION_ID VARCHAR(200),
    CLIENT_SOURCE VARCHAR(200),
    HAS_ANTI_PATTERN BOOLEAN,
    ANTI_PATTERN_REASON VARIANT,
    IS_ANALYZED BOOLEAN DEFAULT FALSE
);



create or replace dynamic table BAD_QUERIES_RAW_IT(
    CAPTURE_ID, CAPTURE_TIMESTAMP, QUERY_ID, WAREHOUSE_NAME, WAREHOUSE_SIZE,
    USER_NAME, ROLE_NAME, QUERY_TYPE, EXECUTION_STATUS, QUERY_DATE,
    TOTAL_ELAPSED_TIME_SEC, TOTAL_CREDITS, TOTAL_COST_USD, GB_SCANNED,
    PERCENTAGE_SCANNED_FROM_CACHE, PARTITION_SCAN_PCT, SPILL_STATUS,
    QUEUE_STATUS, QUERY_TEXT, CLIENT_APPLICATION_ID, CLIENT_SOURCE,
    HAS_ANTI_PATTERN, ANTI_PATTERN_REASON, IS_ANALYZED
) target_lag = '5 minutes' refresh_mode = AUTO initialize = ON_CREATE warehouse = COMPUTE_WH
  cluster by (CAPTURE_ID, QUERY_ID) as
  SELECT * FROM QUERY_OPTIMIZATION_DB.AGENT.BAD_QUERIES_RAW;

create or replace TABLE DAILY_COST_TRENDS (
    TREND_DATE DATE NOT NULL,
    WAREHOUSE_NAME VARCHAR(16777216) NOT NULL,
    TOTAL_QUERIES NUMBER(38,0),
    TOTAL_CREDITS FLOAT,
    TOTAL_COST_USD FLOAT,
    AVG_COST_PER_QUERY FLOAT,
    AVG_ELAPSED_TIME_SEC FLOAT,
    P95_ELAPSED_TIME_SEC FLOAT,
    TOTAL_GB_SCANNED FLOAT,
    SPILL_QUERY_COUNT NUMBER(38,0),
    SPILL_QUERY_PCT FLOAT,
    COST_7D_AVG FLOAT,
    COST_TREND_VS_7D_AVG FLOAT,
    CAPTURED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    primary key (TREND_DATE, WAREHOUSE_NAME)
);

create or replace TABLE PEAK_HOUR_PATTERNS (
    ANALYSIS_DATE DATE,
    WAREHOUSE_NAME VARCHAR(16777216),
    PEAK_HOURS ARRAY,
    OFF_PEAK_HOURS ARRAY,
    BUSIEST_DAY VARCHAR(16777216),
    QUIETEST_DAY VARCHAR(16777216),
    WEEKLY_COST_DISTRIBUTION OBJECT,
    CAPTURED_AT TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

create or replace TABLE QUERY_ANALYSIS_RESULTS (
    ANALYSIS_ID NUMBER(38,0) autoincrement start 1 increment 1 noorder,
    ANALYSIS_TIMESTAMP TIMESTAMP_LTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CAPTURE_ID NUMBER(38,0),
    QUERY_ID VARCHAR(16777216),
    KEY_FINDINGS VARCHAR(4000),
    OPTIMIZATION_SUGGESTIONS VARCHAR(4000),
    SUGGESTED_QUERY_REWRITE VARCHAR(16000)
);


create or replace dynamic table QUERY_ANALYSIS_RESULTS_IT(
    ANALYSIS_ID, ANALYSIS_TIMESTAMP, CAPTURE_ID, QUERY_ID,
    KEY_FINDINGS, OPTIMIZATION_SUGGESTIONS, SUGGESTED_QUERY_REWRITE
) target_lag = '5 minutes' refresh_mode = AUTO initialize = ON_CREATE warehouse = COMPUTE_WH
  cluster by (CAPTURE_ID, QUERY_ID) as
  SELECT * FROM QUERY_OPTIMIZATION_DB.AGENT.QUERY_ANALYSIS_RESULTS;

create or replace TABLE USER_EMAIL_MAPPING (
    USER_NAME VARCHAR(16777216),
    EMAIL_ADDRESS VARCHAR(16777216),
    constraint UQ_USER_NAME unique (USER_NAME)
);

create or replace TABLE USER_ROLES (
    USER_NAME VARCHAR(16777216),
    ROLE_NAME VARCHAR(16777216),
    GRANTED_BY VARCHAR(16777216),
    CREATED_ON VARCHAR(16777216)
);

create or replace view QUERY_OPTIMIZATION_DB.AGENT.V_LATEST_TREND_INSIGHTS(
	INSIGHT_ID,
	ANALYSIS_DATE,
	INSIGHT_TYPE,
	WAREHOUSE_NAME,
	INSIGHT_SUMMARY,
	AI_RECOMMENDATIONS,
	METRICS_SNAPSHOT,
	SEVERITY_SCORE,
	CREATED_AT
) as
SELECT 
    i.INSIGHT_ID,
    i.ANALYSIS_DATE,
    i.INSIGHT_TYPE,
    i.WAREHOUSE_NAME,
    i.INSIGHT_SUMMARY,
    i.AI_RECOMMENDATIONS,
    i.METRICS_SNAPSHOT,
    CASE i.INSIGHT_TYPE
        WHEN 'COST_TREND' THEN i.METRICS_SNAPSHOT:avg_trend_pct::FLOAT
        WHEN 'UTILIZATION_ANOMALY' THEN i.METRICS_SNAPSHOT:queue_pct::FLOAT
        ELSE NULL
    END AS SEVERITY_SCORE,
    i.CREATED_AT
FROM QUERY_OPTIMIZATION_DB.AGENT.AI_TREND_INSIGHTS i
WHERE i.ANALYSIS_DATE >= DATEADD(day, -7, CURRENT_DATE())
ORDER BY i.ANALYSIS_DATE DESC, 
         CASE i.INSIGHT_TYPE 
             WHEN 'UTILIZATION_ANOMALY' THEN 1 
             WHEN 'COST_TREND' THEN 2 
             ELSE 3 
         END;
