create or replace task QUERY_OPTIMIZATION_DB.AGENT.COLLECT_BAD_QUERIES_TASK
	warehouse=COMPUTE_WH
	schedule='60 MINUTES'
	COMMENT='Collects bad queries every hour (no LLM cost)'
	as CALL QUERY_OPTIMIZATION_DB.AGENT.COLLECT_BAD_QUERIES();

create or replace task QUERY_OPTIMIZATION_DB.AGENT.DAILY_TREND_ANALYSIS_TASK
	warehouse=COMPUTE_WH
	schedule='USING CRON 0 6 * * * America/New_York'
	COMMENT='Daily AI-powered trend analysis - runs at 6 AM ET'
	as CALL QUERY_OPTIMIZATION_DB.AGENT.RUN_TREND_ANALYSIS(NULL);

create or replace task QUERY_OPTIMIZATION_DB.AGENT.QUERY_OPTIMIZATION_TASK
	warehouse=COMPUTE_WH
	schedule='60 MINUTES'
	COMMENT='Analyzes bad queries every hour and suggests optimizations using Cortex AI'
	as CALL QUERY_OPTIMIZATION_DB.AGENT.ANALYZE_BAD_QUERIES();

create or replace task QUERY_OPTIMIZATION_DB.AGENT.RUN_AGENT_DAILY_TASK
	warehouse=COMPUTE_WH
	schedule='USING CRON 0 6 * * * UTC'
	COMMENT='Runs the Query Optimizer Agent daily at 6 AM UTC'
	as CALL QUERY_OPTIMIZATION_DB.AGENT.RUN_OPTIMIZATION_AGENT();

create or replace task QUERY_OPTIMIZATION_DB.AGENT.RUN_ANALYSIS_DAILY_TASK
	warehouse=COMPUTE_WH
	schedule='USING CRON 0 6 * * * UTC'
	COMMENT='Analyzes bad queries daily at 6 AM UTC using CORTEX.COMPLETE'
	as CALL QUERY_OPTIMIZATION_DB.AGENT.ANALYZE_AND_SAVE_QUERIES();

create or replace task QUERY_OPTIMIZATION_DB.AGENT.SEND_ALERT_EMAIL_TASK
	warehouse=COMPUTE_WH
	when SYSTEM$STREAM_HAS_DATA('QUERY_OPTIMIZATION_DB.AGENT.ALERT_QUEUE_STREAM')
	as CALL QUERY_OPTIMIZATION_DB.AGENT.PROCESS_ALERT_QUEUE();
